services:
  db-service:
    container_name: 'RhythmDB'
    image: 'postgres'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=RhythmDB
    ports:
      - "2345:5432"